---
- name: Configure users
  hosts: demo
  remote_user: root
  become: yes
  gather_facts: yes
 
  vars_files:
    - users.yml
 
  tasks:
    - name: Create a login user
      user:
         name: "{{ item.name }}"
         password: "{{ item.password | password_hash('sha512') }}"
         uid:  "{{ item.uid }}"
         group:  "{{ item.group }}"
         state: present
         shell: /bin/bash
      with_items: "{{ user_list }}"
