---
- name: Install PIP module using Ansible pip module
  hosts: local
  remote_user: root
  become: yes
  gather_facts: yes

  tasks:
  - name: Installing python libraries in Ansible
    pip:
      name: bottle
      executable:  /opt/rh/python27/root/bin/pip
    environment:
      LD_LIBRARY_PATH: /opt/rh/python27/root/lib64
