---
- name: Update APT cache
  hosts: all
  remote_user: root
  become: yes
  environment:
    LC_ALL: C
    LANG: C

  tasks:

  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=600

  - name: List upgradable packages
    command: apt list --upgradable
